# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# virtualenv python
alias act_mini='source ~/github/mini/.venv/bin/activate'
alias act_meta='source ~/github/metaprogram/venv/bin/activate'
alias dact="deactivate"

# zsh
alias zshrc="nvim ~/nixos-config/users/hq0x/home/zshrc"
alias zshre="source ~/nixos-config/users/hq0x/home/zshrc && echo 'Reloaded shell'"
cd() {
  builtin cd "$@" && pwd && ls
}
alias back="cd /home/hq0x/github"
alias matrix="cmatrix -C cyan"
alias clo='fc -ln -1 | zsh 2>&1 | xclip -selection clipboard' 
alias copy='xclip -selection clipboard <'

# Connect 
alias mini="ssh -i ~/.ssh/mini hq0x@plsfpwrapp01.dc.sll.se"
alias big="ssh -i ~/.ssh/mini hq0x@plsosedwdb02.dc.sll.se"
# python
alias py="python3.12"

# NixOS config
alias upgrade="sudo nixos-rebuild switch --flake ~/nixos-config#hq0x"
alias modify="cd /home/hq0x/nixos-config/users/hq0x"

# Ruff
alias rf="ruff format"
alias rc="ruff check"

#ripgrep
alias rgf='rg --files | rg'

#kubectl
alias k="kubectl"
alias kg="kubectl get"
alias kgp="kubectl get pods"
alias kdp="kubectl delete pod "

# 1password
#alias 1p="eval $(op signin)"
#eval "$(op completion zsh)"; compdef _op op

# Github
export PATH='/home/hq0x/.duckdb/cli/latest':$PATH
alias rebase="git pull --rebase" # Rebase so to not introduce conflict
alias start="act_mini && rf . && git add . && git commit"
alias fix='act_mini && ruff format . && echo "✓ Ran ruff format" && git add . && echo "✓ Files staged" && git status && git commit -m "fix" && git push'
alias lint="act_mini && ruff check --fix ."


plugins=(git z pip helm docker colored-man-pages 1password)



#### -------------Installed Shit--------------- ####

# tmux
# ripgrep
# ranger
# vim
# fzf
# tree
# btop

#### ---------- On Startup ---------- ####

#export PINAPPLE_PASSWORD=believe-BAGNIO-filtrate-tamp-shire-fountain-tower-sinter-folklore &&
#export PINAPPLE_USER=miniplattformen_pinapple_encrypt &&
#export PINAPPLE_URL=https://pinapple.apps.ocp.mta.karolinska.se
#export REQUESTS_CA_BUNDLE="/home/hq0x/certs/pinapple_cert.pem"

zex() {
    if [ -n "$1" ]  # Check if a parameter was provided
    then
        kubectl exec -it "$1" -- /bin/zsh
    else
        echo "Usage: zex [pod_name]"
    fi
}

eval "$(ssh-agent -s)" > /dev/null 2>&1
ssh-add ~/.ssh/id_ed25519 2>/dev/null

# Some nvim shit from install
export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
export LD_LIBRARY_PATH=/run/current-system/sw/lib:$LD_LIBRARY_PATH
task list

DISABLE_UNTRACKED_FILES_DIRTY="true" # This should help with removing untacked files from git status
